spring:
  datasource:
    url: jdbc:h2:file:./data/users_api
    driverClassName: org.h2.Driver
    username: augusto
    password: abc123
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect